### ISSUE TITLE
Clarification on 0-based to 1-based Coordinate Conversion in SpliSER

### ISSUE THREAD

**Issue by mrunyan1** [CraigIDent/SpliSER#5]
From my understanding of the code, Sites are created for the start and end coordinates of each junction listed in the BED files generated by regtools. BED files are typically 0-based and I have not found anywhere in the code where sites are adjusted to 1-based indexing. Are/should start positions of junctions be adjusted by one?

**Comment by CraigIDent** [comment]
Hi mrunyan,
I'm not sure exactly what the practical difference between 0-based and 1-based would be here. I'll clarify a bit what SpliSER is actually reporting.

Take for example a bed file line like this:

Chr1 	11458967	11459214	JUNC00012595	7	+	11458967	11459214	255,0,0	2	90,55	0,192

The junction feature begins at 11458967, and we add 90 to find the "left" splice site position = 11459057
The junction feature ends at 11459214, and we subtract 55 to find the "right" splice site position = 11459159

So in both cases, SpliSER will record the splice site position as the nucleotide in your reference genome immediately "left" of where the splicing occurs. 
This is true also for junctions on the minus strand. It will be the position "genomically left" of where the splicing occurs, that is reported.

eg. 
Plus-strand intron 
>>EXON1...GTACAAT|GTAATG.....intron....TTTCAG|GCATGA.....EXON2>>
                                 ^                                              ^  
Minus-strand intron 
<<EXON2...TCATGC|CTGAAA.....intron....CATTAC|ATTGTAC.....EXON1<<
                                ^                                              ^
(Splice sites marked with | symbol.Reported positions marked with ^ symbol)

In some of our analyses, we wanted to know distances of intronic SNPs from the splice site positions. In this case we added 1 to the position of plus-strand donor sites and minus-strand acceptor sites, so that the positions always pointed to the first and last nucleotides of an intron. 
If you need help scripting something to edit the positions like this, send me a follow-up message/email and we can discuss how to do it.
